services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3000"  # Host port 3001 maps to container 3000
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/notes

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:5173"  # Host port 8080 maps to container 5173
    depends_on:
      - backend

volumes:
  mongo-data:
