version: '3.8'

services:
  backend:
    image: minahil48/note-app-backend
    ports:
      - "3001:3000"      # Use 3001 on host, container still 3000
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/notes

  frontend:
    image: minahil48/note-app-frontend
    ports:
      - "8080:5173"     # Use 8080 on host for frontend
    depends_on:
      - backend

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
