services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/notes
    volumes:
      - /c/note-app/backend:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:5173"
    depends_on:
      - backend
    volumes:
      - /c/note-app/frontend:/app

volumes:
  mongo-data:
